# Generated by Django 5.0.2 on 2024-02-27 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_rename_seats_transport_columns_ticket_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='route',
        ),
    ]
