# Generated by Django 5.0.2 on 2024-02-27 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_remove_trip_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='bus.route'),
            preserve_default=False,
        ),
    ]
