# Generated by Django 5.0.2 on 2024-02-27 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0004_trip_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='transport',
        ),
    ]
