# Generated by Django 5.0.2 on 2024-02-27 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_remove_company_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='transport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bus.transport'),
        ),
    ]
