# Generated by Django 5.0.2 on 2024-02-27 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0006_company_transport'),
    ]

    operations = [
    ]
