# Generated by Django 5.0.2 on 2024-02-27 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0008_transport_columns_transport_rows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='columns',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='rows',
        ),
    ]
