# Generated by Django 5.0.2 on 2024-02-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0009_remove_transport_columns_remove_transport_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='columns',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transport',
            name='rows',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
